settings:
  telemetry_enabled: true
active_modules:
  ev_api:
    connections:
      ev_manager:
        - implementation_id: ev_manager
          module_id: ev_manager
    module: EvAPI
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
  #auth:
  #  config_module:
  #    connection_timeout: 10
  #    prioritize_authorization_over_stopping_transaction: true
  #    selection_algorithm: FindFirst
  #    ignore_connector_faults: true
  #  connections:
  #    evse_manager:
  #      - implementation_id: evse
  #        module_id: connector_1
  #    token_provider:
  #      - implementation_id: main
  #        module_id: token_provider
  #    token_validator:
  #      - implementation_id: main
  #        module_id: token_validator
  #  module: Auth
  ev_manager:
    config_module:
      auto_enable: true
      auto_exec: false
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 30;unplug
      connector_id: 1
    connections:
      ev:
        - implementation_id: ev
          module_id: iso15118_car
      ev_board_support:
        - implementation_id: ev_board_support
          module_id: connector_1_powerpath
      slac:
        - implementation_id: ev_slac
          module_id: slac
    module: EvManager
  
  iso15118_car:
    config_module:
      device: auto
      supported_ISO15118_2: true
    connections: {}
    module: PyEvJosev
  
  persistent_store:
    config_module:
      sqlite_db_file_path: everest_persistent_store.db
    connections: {}
    module: PersistentStore
  setup:
    config_module:
      initialized_by_default: true
      localization: true
      online_check_host: lfenergy.org
      setup_simulation: true
      setup_wifi: false
    connections:
      store:
        - implementation_id: main
          module_id: persistent_store
    module: Setup
  slac:
    module: EvSlac
    config_implementation:
      main:
        device: eth0

  connector_1_powerpath:
    config_module:
      connector_id: 1
    connections: {}
    module: YetiSimulator
    telemetry:
      id: 1
